### ISSUE TITLE
Erro ao cadastrar o produto

### ISSUE THREAD

**Issue by victor4pinheiro** [Fernandafmsf/Projeto-estoque#1]
Olá! Eu sou o shaka (@shaka_042) que conversou contigo a respeito do teu projeto e já consegui identificar o problema. Trata-se de uma má implementação da PSR4, pois apesar da definição do autoload no composer.json, para que haja uma navegação e acesso entre os arquivos, é necessário o uso dos namespaces. Veja o exemplo abaixo:

![image](https://github.com/Fernandafmsf/Projeto-estoque/assets/60495567/7f83fe98-3b74-4307-9b46-195d16117dfd)

Mas como isso impede o cadastro? Porquê não carrega o arquivo da Model. Simplesmente isso.

Outro ponto é que a tela de cadastro bem como as outras precisam estar dentro do src, pois é através dele que o composer fará o loading correto, contudo, surge um novo problema: rotas. 

Apesar de conseguirmos usar a aplicação do lado do servidor (Model/DAO/Controller), no lado do cliente (diga-se frontend), a lógica de navegação muda, pois como navegaremos entre sites se não podermos usar o caminho absoluto já que pode mudar de acordo com o ambiente e não ocorre o autoloading por parte do composer se não estiver usando namespace (e não usamos eles nas telas)? A resposta é usar roteamento, mas para isso, aumenta a complexidade da aplicação.

Como você quer fazer uma aplicação "pura", surgem duas soluções: usar query params (foi o que eu utilizei na primeira vez que fiz um projeto similar ao teu) ou criar um arquivo de rota e adicionar um .htaccess (para Apache) ou configurar o nginx.conf (para Nginx) para fazer o redirecionamento. A escolha é tua, mas em ambos tu vai aprender bastante.

Eu mesmo sinto dificuldade em fazer o segundo, pois uso o Nginx no Linux e tenho uma dificuldade enorme com ele (mas já vi adicionar módulos), mas se tu usa XAMPP, então será bem mais fácil.

Segue um exemplo (sem rotas): https://github.com/victor4pinheiro/sample_psr4_php

OBS.: Tenho outras recomendações, mas prefiro deixar essa issue focada só nesse problema de criação.

**Comment by victor4pinheiro** [comment]
Em qualquer dúvida, estou disponível para orientar no desenvolvimento do projeto.

**Comment by Fernandafmsf** [comment]
Olá, Victor! Primeiramente, muito obrigada pelo apoio! 
Fiz um fork do repositório que você mencionou acima e comecei a fazer alguns testes para entender melhor como tudo funciona. 
Você mencionou sobre o namespace e eu cheguei a tentar dessa forma no meu projeto, me levando ao mesmo erro de "objeto não encontrado". Pensando nisso, fiz o mesmo com o seu repositório. Fiz um fork dele e explorei bastante o formato que você usou. Depois tentei implementar com o formato que eu estava usando, que consistia no form enviando o post para o arquivo do controller, ao inves de para ele mesmo. Quando mudei para esse formato parou de funcionar. Teria a ver com as rotas que você mencionou? 

Se quiser ver a forma que fiz, segue o fork, está na branch chamada "testando": https://github.com/Fernandafmsf/sample_psr4_php/tree/testando

**Comment by victor4pinheiro** [comment]
Sim, pois como os arquivos são localizados e carregados através da namespace, então o próprio conceito de acesso de caminho relativo para um arquivo não é feito da mesma forma que seria feito usando por exemplo: `<a href="forms.php">Teste</a>`, pois para o autoloading, ele não sabe onde está esse forms.

Com isso, precisariamos de uma maneira intermediária para carregar esse arquivo, que seria justamente através de um arquivo de rota, pois ele pegaria a url, identificaria qual que queremos acessar e carregaria dinamicamente esse arquivo. E com isso, até mesmo a nomenclatura mudaria, pois viraria para isso: `<a href="cadastrar">Teste</a>`.

Perceba bem que agora eu não me importo com a extensão do arquivo ou qualquer outra coisa, pois é função da rota achar o arquivo cadastrar.php e carregar ela.

**Comment by Fernandafmsf** [comment]
Entendi agora! Muito obrigada! Vou estudar mais a fundo e aplicar posteriormente.

**Comment by victor4pinheiro** [comment]
Vou fechar essa issue, pois ela já atendeu ao seu critério.
